Frontend: Add location features
OreCart/OreCart-App pull request #100
Opened 2023-12-23 04:46 UTC by OxygenCobalt

- Handle when location permissions are not present and indicate them accordingly
- Make route items actively show the nearest stop and the van arrival time to that stop

Limitations:
- Since I assume the van arriving to the stop is the closest van, this may result in the arrival time being completely out of wack if a departing van is closer to the stop than an arriving van.

2023-12-27 01:56 UTC, ezrichards approved these changes

2023-12-27 02:03 UTC, OxygenCobalt commented
@shanecranor Please review

2023-12-28 22:47 UTC, shanecranor requested changes

2023-12-28 22:47 UTC, shanecranor commented on frontend/src/features/location/util.ts
> +    return `${Math.round(distance)} mi`;
We should add more precision here using .toFixed, the bus route itself is only a few miles and I'm not sure 1 mile increments is enough precision

2023-12-28 22:48 UTC, shanecranor commented
good to merge after fix/discussion

2023-12-30 17:39 UTC, shanecranor approved these changes

2023-12-30 17:40 UTC, merged