Generic Caching
OreCart/OreCart-App pull request #103
Opened 2023-12-24 01:36 UTC by tbwrigh

2023-12-26 22:22 UTC, OxygenCobalt requested changes
Overall good

2023-12-26 22:22 UTC, OxygenCobalt commented on .github/workflows/python-lint.yaml
> +      - run: isort --profile black --check --diff ./backend/
This was intentional. Isort behaves differently depending on if it's aware of pip dependencies and not, so currently isort is not correctly checking 3rd party library import order on the CI.

2023-12-27 01:55 UTC, ezrichards approved these changes
Looks good overall.

2023-12-27 01:55 UTC, ezrichards commented on backend/src/caching/memcached.py
> +            raise ValueError("memcache_address not in config")
I'm a little wary of 1) these error messages and 2) the fact that we're raising errors anyways; we want to, as they say, crash/fail gracefully. If something goes wrong with the cache, the entire backend could potentially go down.

2023-12-27 02:03 UTC, shanecranor approved these changes

2023-12-27 02:03 UTC, shanecranor commented
looks good assuming you tested it

2024-01-01 04:32 UTC, OxygenCobalt commented on .github/workflows/python-lint.yaml
> +      - run: isort --profile black --check --diff ./backend/
Alright, I'll just leave this as-is and run isort in the broken mode. I'll figure out the issue later in-person.

2024-01-01 04:33 UTC, OxygenCobalt approved these changes

2024-01-05 19:15 UTC, OxygenCobalt requested changes
Actually, one change: You need to add the new environment variables to the docker compose file so it doesn't break.

2024-01-05 21:29 UTC, OxygenCobalt approved these changes

2024-01-05 21:29 UTC, merged