backend: convert raw sql to sqlalchemy
OreCart/OreCart-App pull request #124
Opened 2024-01-18 23:20 UTC by OxygenCobalt

EXCEPT when downgrading, as we need to cascade drop and sqlalchemy does not support doing that for some reason

2024-01-20 04:07 UTC, ezrichards approved these changes

2024-01-20 07:43 UTC, tbwrigh requested changes

2024-01-20 07:43 UTC, tbwrigh commented on backend/alembic/versions/87f033493d8b_create_schedules_table.py
> -	        end_time timetz NOT NULL CHECK (end_time > start_time),
I don't think the end > start check got moved over

2024-01-20 07:43 UTC, tbwrigh commented on backend/alembic/versions/b8ce06a37505_create_ridership_table.py
> +        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
Why are these foreign keys done differently than the other tables?

2024-01-20 07:43 UTC, tbwrigh commented on backend/alembic/versions/f1a02e4febad_create_vans_table.py
> +        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="SET NULL"),
Again, why is this foreign key done different?

2024-01-20 07:43 UTC, tbwrigh commented on backend/alembic/versions/b8ce06a37505_create_ridership_table.py
> +        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
Also, this is probably a longer discussion, but I doubt we ever want to delete analytics. @ezrichards thoughts?

2024-01-20 07:43 UTC, tbwrigh commented on backend/alembic/README.md
> +This will generate a new file called something like "abcdef123456_descriptive_message_here.py". It will contain an "upgrade" method should take the current table state and update it to the new table
What does "since SQLAlchemy does not support `CASCADE` well." mean? In what does it not support `CASCADE` well?

2024-01-25 02:07 UTC, tbwrigh approved these changes

2024-01-25 02:07 UTC, merged