Table creation migrations
OreCart/OreCart-App pull request #27
Opened 2023-10-04 05:03 UTC by grantlemons

Uhh I didn't realize that @C00perN was already doing the analytics, I made these in the process of making the ERD.

Summary:
- Created all tables discussed today
- Configured relationships between tables
- Created constraints on certain fields

2023-10-04 21:20 UTC, grantlemons commented
Renamed analytics table to ridership as discussed in #orecart-backend

2023-10-05 00:57 UTC, tbwrigh requested changes

2023-10-05 00:59 UTC, grantlemons commented on backend/migrations/create_stops_table.sql
> +	active bool NOT NULL,
id is stop_id

2023-10-05 00:59 UTC, grantlemons commented on backend/migrations/create_routes_table.sql
> +	UNIQUE (name)
that's just id

2023-10-05 01:10 UTC, grantlemons commented on backend/OreCart Database ER Diagram.erd
stops has an active column

2023-10-05 01:24 UTC, grantlemons commented on backend/OreCart Database ER Diagram.erd
now that I think about it, a table to disable routes between times makes sense, but I still think mapping detours is unneeded, especially since it minimizes the amount of admin intervention

2023-10-05 14:43 UTC, OxygenCobalt approved these changes
I think this looks pretty good as a first iteration. I do think we will probably need to make the route/stop disabling more robust, but that requires stakeholder feedback.

2023-10-05 17:24 UTC, grantlemons commented
Marking as draft in favor of #29

2023-10-05 18:29 UTC, grantlemons commented on backend/OreCart Database ER Diagram.erd
Now implemented in #29.

2023-10-06 21:06 UTC, grantlemons commented
Marking closed because I don't actually want this merged (#29)

2023-10-06 21:06 UTC, closed without merging