Memcached
OreCart/OreCart-App pull request #91
Opened 2023-12-19 03:22 UTC by tbwrigh

2023-12-19 03:32 UTC, tbwrigh commented
@OxygenCobalt can you push new location updates? I don't know how to send a byte body in postman.

2023-12-19 16:04 UTC, OxygenCobalt commented
@tbwrigh Here's a script

```py
import struct
from datetime import datetime, timezone
from time import sleep
import requests

coords = [
    (39.7518902, -105.2209817),
    (39.7519935, -105.2208025),
    (39.7521685, -105.2204875),
    (39.7523451, -105.2201381),
    (39.7525108, -105.2198471),
    (39.7526269, -105.2196366),
]

while True:
    for lat, lon in coords[:-1]:
        print(lat, lon)
        timestamp = int(datetime.now(timezone.utc).timestamp())  # Current time in seconds since the Epoch as a float
        # Pack the values into a bytes object
        body = struct.pack("!ldd", timestamp, lat, lon)


        url = "http://localhost:8000/vans/location/0"
        headers = {"Content-Type": "application/octet-stream"}

        response = requests.post(url, data=body, headers=headers)

        print(response.status_code)

        sleep(2)
    for lat, lon in coords[1:][::-1]:
        print(lat, lon)
        timestamp = int(datetime.now(timezone.utc).timestamp())  # Current time in seconds since the Epoch as a float
        # Pack the values into a bytes object
        body = struct.pack("!ldd", timestamp, lat, lon)


        url = "http://localhost:8000/vans/location/0"
        headers = {"Content-Type": "application/octet-stream"}

        response = requests.post(url, data=body, headers=headers)

        print(response.status_code)

        sleep(2)
```

2023-12-19 16:45 UTC, OxygenCobalt requested changes

2023-12-19 16:45 UTC, OxygenCobalt commented on backend/src/handlers/vans.py
> +    #     raise HTTPException(detail="Van not found", status_code=404)
Why is this commented?

2023-12-19 16:45 UTC, OxygenCobalt commented on backend/src/handlers/vans.py
> +    print(len(body))
Left some printf debugging in it seems

2023-12-19 16:45 UTC, OxygenCobalt commented on backend/src/main.py
> +    app.state.memcache_client = memcache.Client([("127.0.0.1", 11211)])
Are you sure we want to hard-code these?

2023-12-22 19:36 UTC, tbwrigh commented
Decided not to use memcached.

2023-12-22 19:36 UTC, closed without merging